#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list
# Displays "FizzBuzz" when the num is a multiple of both 3 and 5
# Displays "Fizz" when the num is a multiple of 3
# Displays "Buzz" when the num is a multiple of 5 Otherwise

for num in {1..100}
do
	if [[ $num%3 -eq 0 && $num%5 -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $num%3 -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $num%5 -eq 0 ]]
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
