#!/usr/bin/env bash
# Let's install the ufw firewall and setup a few rules on web-01

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufww default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
